language: python
python:
  - 3.5
notifications:
  email: false

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: 
  - cd operations/ekos/tests
  - py.test
