sudo: required
language: python
python:
  - 3.5
notifications:
  email: false

before_install:
  - sudo apt-get install -y swig

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: 
  - cd operations/ekos
  -  python3 -m unittest
