language: python
python: 2.7

env:
    global:
        - NUMPY_VERSION=1.11
        - ASTROPY_VERSION=stable
        - CONDA_INSTALL='conda install -c astropy --yes'
        - PIP_INSTALL='pip install'
        - MINICONDA_HOME='/home/travis/miniconda'

before_install:
    # Use utf8 encoding. Should be default, but this is insurance against
    # future changes
    - export PYTHONIOENCODING=UTF8
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $MINICONDA_HOME
    - export PATH=$MINICONDA_HOME/bin:$PATH
    - conda update --yes conda

install:

    - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy nose
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
    - pip install ccdproc
    - pip install pep8 python-coveralls
    - pip install .

script:

  - THEANO_FLAGS=floatX=float32 nosetests --with-coverage --cover-package=theanets --logging-level=INFO

after_success:
  - coveralls
