dist: trusty
sudo: required
language: python
python:
  - 3.5
notifications:
  email: false

before_install:
  - sudo add-apt-repository universe
  - apt-cache policy
  - sudo apt-get update
  - sudo apt-cache search indi
  - sudo apt-get install -y indi-full
  - sudo apt-get install -y swig

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: 
  - cd operations/ekos/tests
  - py.test
