#!/bin/bash

cd ~/code/github/bh-observatory/data-reduction/calibration
python3 calibrateLightFrames.py
cd ~/code/github/bh-observatory/data-reduction
python3 addFitsObjectToFilename.py
#python solveAll.py
echo 'Reduction Complete'

